### ISSUE TITLE
Issue with stb.freq thresh parameter in version 0.6.0 and 0.7.0

### ISSUE THREAD

**Issue by rserran** [chris1610/sidetable#17]
Chris,

Hi!

First, thanks for providing a tool to quickly summarize and order categorical counts!

I'm experiencing an issue with the thresh parameter in stb.freq.  In version 0.5.0, it is working as shown in the vignette and various articles. However, when upgrading to 0.6.0 and the later version 0.7.0, this happens:

        <categorical column> count	percent	cumulative_count	 cumulative_percent
0	Other Services	      32978	100.0	32978	                 100.0

When I omit the thresh parameter, it shows all the categories with their respective counts and percentages. I also tried to change the feature to categorical, but the issue persists. Once I downgrade to 0.5.0, the issue disappears!

Any thoughts about what change from 0.5.0 to 0.6.0 that is causing this?

**Comment by chris1610** [comment]
Quick question, what value are you passing the thresh?  It should be a whole number now, that is a change I made so that if you want to have the threshold at 20% you should use 20 not .2. That's the biggest change and some of the earlier tutorials show the .2 version.

If that's not the case, can you post a data set that shows this behavior?

**Comment by rserran** [comment]
I ran stb.freq with thresh=96 (96%) and it works.

Thanks again!
